/* Generated By:JavaCC: Do not edit this line. Ec2InstanceParserConstants.java */
package com.edigley.cloudsim.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Ec2InstanceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A_COLCHETE = 6;
  /** RegularExpression Id. */
  int F_COLCHETE = 7;
  /** RegularExpression Id. */
  int X = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int DECIMAL = 10;
  /** RegularExpression Id. */
  int VALUE = 11;
  /** RegularExpression Id. */
  int ALIAS = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 14;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"[\"",
    "\"]\"",
    "\"x\"",
    "<INTEGER>",
    "<DECIMAL>",
    "<VALUE>",
    "<ALIAS>",
    "<STRING>",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 17>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
